### ISSUE TITLE
Still crashes on openning level-selection (single player) screen

### ISSUE THREAD

**Issue by MUYUTwilighter** [Silk-MC/Silk-API#2]
Minecraft: 1.20.1
Fabric Loader: 0.15.6
Fabric API: 0.91.0
Silk API: silk-api-1.20-0.2.0+fixed
Other mods installed on tested client:
    - Spontaneous-Replace-1.20-0.5.5+bu
Crash report: https://pastebin.com/rBqGbz6P

The issue is posted here because similar crash info is displayed whether the Spontaneous Replace is installed or not.
I'm not sure whether the crash happenned in level-selection screen or level-create screen, since both of them could be invoked when clicking on "Single Player" button when play MC for the first time.
Quite a few mods only provide maintainance for 1.20.1 or older, so fixing this issue would help me a lot in assembling my modpack, for which I would sincerely appreciate!

**Comment by Saikel-Orado-Liu** [comment]
> Minecraft: 1.20.1 Fabric Loader: 0.15.6 Fabric API: 0.91.0 Silk API: silk-api-1.20-0.2.0+fixed Other mods installed on tested client: - Spontaneous-Replace-1.20-0.5.5+bu Crash report: https://pastebin.com/rBqGbz6P
> 
> The issue is posted here because similar crash info is displayed whether the Spontaneous Replace is installed or not. I'm not sure whether the crash happenned in level-selection screen or level-create screen, since both of them could be invoked when clicking on "Single Player" button when play MC for the first time. Quite a few mods only provide maintainance for 1.20.1 or older, so fixing this issue would help me a lot in assembling my modpack, for which I would sincerely appreciate!

I'm very sorry for your problem and I will resolve it as soon as possible. You can temporarily solve this problem by adding an old archive to the save folder first.

**Comment by Saikel-Orado-Liu** [comment]
> Minecraft: 1.20.1 Fabric Loader: 0.15.6 Fabric API: 0.91.0 Silk API: silk-api-1.20-0.2.0+fixed Other mods installed on tested client: - Spontaneous-Replace-1.20-0.5.5+bu Crash report: https://pastebin.com/rBqGbz6P
> 
> The issue is posted here because similar crash info is displayed whether the Spontaneous Replace is installed or not. I'm not sure whether the crash happenned in level-selection screen or level-create screen, since both of them could be invoked when clicking on "Single Player" button when play MC for the first time. Quite a few mods only provide maintainance for 1.20.1 or older, so fixing this issue would help me a lot in assembling my modpack, for which I would sincerely appreciate!

A new version will be released soon, fixing reported known issues

**Comment by Phoupraw** [comment]
Still crash.
[crash-2024-02-18_15.39.47-client.txt](https://github.com/Silk-MC/Silk-API/files/14321537/crash-2024-02-18_15.39.47-client.txt)

**Comment by Saikel-Orado-Liu** [comment]
> 还是崩溃。 [crash-2024-02-18_15.39.47-client.txt](https://github.com/Silk-MC/Silk-API/files/14321537/crash-2024-02-18_15.39.47-client.txt)

are you sure? The latest version is on modrinth, and the SR and API must be updated. There have been previous user reports that this issue has been fixed.

**Comment by Saikel-Orado-Liu** [comment]
Apparently your report has not been updated to the new version

**Comment by Phoupraw** [comment]
> > 还是崩溃。 [crash-2024-02-18_15.39.47-client.txt](https://github.com/Silk-MC/Silk-API/files/14321537/crash-2024-02-18_15.39.47-client.txt)
> 
> are you sure? The latest version is on modrinth, and the SR and API must be updated. There have been previous user reports that this issue has been fixed.

The latest version in mc1.20.1 I found in modrinth is `0.2.1`.

**Comment by Phoupraw** [comment]
> Apparently your report has not been updated to the new version

`0.2.1+fixed` is for `1.20.3-1.20.4`, but version I want is `1.20.1`.

**Comment by Saikel-Orado-Liu** [comment]
> > Apparently your report has not been updated to the new version
> 
> `0.2.1+fixed` is for `1.20.3-1.20.4`, but version I want is `1.20.1`.

you are right

**Comment by Saikel-Orado-Liu** [comment]
However, other users have reported that this problem has been fixed. The acquisition is due to mod conflict, which is an extremely difficult problem to troubleshoot.

**Comment by Saikel-Orado-Liu** [comment]
I will do my best

**Comment by Phoupraw** [comment]
好了，我发现这很可能是《彗星》的问题，我把它卸载了之后就好了（只不过点击“单人游戏”按钮后，存档列表界面还是要很久才能加载完毕）。之前一进世界就崩的《钠》也正常了。

**Comment by Saikel-Orado-Liu** [comment]
> 好了，我发现这很可能是《彗星》的问题，我把它卸载了之后就好了（只不过点击“单人游戏”按钮后，存档列表界面还是要很久才能加载完毕）。之前一进世界就崩的《钠》也正常了。

离谱，中国人就说中国话呗，我也是中国人，哈哈哈
要加载是正常的，因为加装了检测世界是否为模组世界的功能。
而且只有第一次要加载一下初始化，之后就秒进的。
