### ISSUE TITLE
Crash on loading world or by creating a new one

### ISSUE THREAD

**Issue by Zafpyr** [Silk-MC/Silk-API#3]
Minecraft: 1.20.2
Fabric Loader: 0.15.10
Fabric API: 0.91.6
Silk API: silk-api-1.20.2-0.2.0+fixed
Other mods installed on tested client: None
Crash report: https://pastebin.com/qu352vzT

Crash happens upon clicking on 'play selected world' or by creating a new world. 
Temporary fix I've found is to downgrade to silk-api-1.20.2-0.1.3+fixed.

**Comment by Saikel-Orado-Liu** [comment]
> Minecraft: 1.20.2 Fabric Loader: 0.15.10 Fabric API: 0.91.6 Silk API: silk-api-1.20.2-0.2.0+fixed Other mods installed on tested client: None Crash report: https://pastebin.com/qu352vzT
> 
> Crash happens upon clicking on 'play selected world' or by creating a new world. Temporary fix I've found is to downgrade to silk-api-1.20.2-0.1.3+fixed.

You need to address this issue by updating to the new version. The Silk API for the new version is only released on Modrinth, so you'll need to download it from there.

**Comment by Zafpyr** [comment]
Thank you! 

Is inclusion of the new version in mod packs allowed? 
If so, Is the mod pack only allowed to be distributed via Modrinth?

**Comment by Saikel-Orado-Liu** [comment]
Yes, distributing mod packs on Modrinth can bring higher earnings for authors, so I highly recommend releasing mod packs on Modrinth. 
However, I understand that some people prefer CurseForge (CF), so I will also regularly upload new versions to CF. 
Currently, version 1.20-0.3.1 has been released on CF to address this issue.

**Comment by Zafpyr** [comment]
My pack is dependent on MC 1.20.2, but silk-api 0.3.1 is only for MC 1.20.5

silk-api-1.20.2-0.1.3+fixed seems to working well though.

**Comment by Saikel-Orado-Liu** [comment]
thanks

**Comment by Saikel-Orado-Liu** [comment]
do you want me to upload version 1.20.2 to CF?

**Comment by Zafpyr** [comment]
Yes please, If you wouldn't mind.

**Comment by Saikel-Orado-Liu** [comment]
Alright, but version 1.20.2 will no longer receive updates, just a heads up.

**Comment by Zafpyr** [comment]
Sweet! Thank you.
