### ISSUE TITLE
Install silkapi, waystone Repeated activation

### ISSUE THREAD

**Issue by zc1108aaa** [Silk-MC/Silk-API#4]
step
The log contains,
Open the menu,
Close the menu,
Open wayston,
Close waystone,
Repeated activation
[latest (1).log](https://github.com/Silk-MC/Silk-API/files/15472542/latest.1.log)

**Comment by Saikel-Orado-Liu** [comment]
Currently, the API is undergoing a major architectural overhaul. I will try to address similar issues in the new architecture version.
